version: '3'
services:
  logic:
    image: chirag0401/sa-logic
    container_name: sa-logic
    build:
      context: ./sa-logic
    ports:
      - 5050:5000
  webapp:
    image: chirag0401/sa-webapp
    container_name: sa-webapp
    build:
      context: ./sa-webapp
    ports:
      - 8080:8080
    environment:
      - SA_LOGIC_API_URL=http://18.236.121.106:5050
  frontapp:
    image: chirag0401/sa-frontend
    container_name: sa-frontend
    build: 
      context: ./sa-frontend
    ports:
      - 80:80
